=== iamsebastn/dhbwPortfolio/app/structure.dtd
<!ELEMENT Bestellung (Kunde, Artikel)>

<!ELEMENT Kunde (Name, Anschrift)>
<!ATTLIST Kunde isStudent (true | false) #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Anschrift (Strasse, Hausnummer, PLZ, Ort)>

<!ELEMENT Strasse (#PCDATA)>
<!ELEMENT Hausnummer (#PCDATA)>
<!ELEMENT PLZ (#PCDATA)>
<!ELEMENT Ort (#PCDATA)>

<!ELEMENT Matrikelnummer (#PCDATA)>
<!ELEMENT Studienort (#PCDATA)>

<!ELEMENT Artikel (Pizza+)>
<!ELEMENT Pizza (Belag)+>
<!ELEMENT Belag (#PCDATA)>

<!ATTLIST Belag isSpicy (true | false) #REQUIRED>

<!-- 
    ? = kein oder 1 Element ist erlaubt

    * = Kein oder mehrere Elemente sind erlaubt

    + = ein oder mehrere Elemente erforderlich
-->

=== iamsebastn/dhbwPortfolio/app/nonStudentOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bestellung SYSTEM "structure.dtd">

<Bestellung>
    <Kunde isStudent="false">
        <Name>Max Muster</Name>
        <Anschrift>
            <Strasse>GibtesNicht</Strasse>
            <Hausnummer>1</Hausnummer>
            <PLZ>21624</PLZ>
            <Ort>Buxtehude</Ort>
        </Anschrift>
    </Kunde>

    <Artikel>
        <Pizza>
            <Belag isSpicy="false">Schinken</Belag>
            <Belag isSpicy="false">Ananas</Belag>
            <Belag isSpicy="false">Pepperoni</Belag>
            <Belag isSpicy="false">KÃ¤se</Belag>
        </Pizza>
    </Artikel>
</Bestellung>

=== iamsebastn/dhbwPortfolio/app/studentOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bestellung SYSTEM "structure.dtd">

<Bestellung>
    <Kunde isStudent="true">
        <Name>Sebastian</Name>
        <Anschrift>
            <Strasse>Sophienstraße</Strasse>
            <Hausnummer>29</Hausnummer>
            <PLZ>76133</PLZ>
            <Ort>Karlsruhe</Ort>
        </Anschrift>
    </Kunde>

    <Artikel>
        <Pizza>
            <Belag isSpicy="false">Schinken</Belag>
            <Belag isSpicy="false">Käse</Belag>
            <Belag isSpicy="true">Salami</Belag>
            <Belag isSpicy="false">Pepperoni</Belag>
        </Pizza>
        <Pizza>
            <Belag isSpicy="false">Schinken</Belag>
            <Belag isSpicy="false">Käse</Belag>
            <Belag isSpicy="false">Pilze</Belag>
        </Pizza>
        <Pizza>
            <Belag isSpicy="false">Salami</Belag>
            <Belag isSpicy="false">Käse</Belag>
            <Belag isSpicy="false">Pilze</Belag>
            <Belag isSpicy="false">Ananas</Belag>
        </Pizza>
    </Artikel>
</Bestellung>
